language: haskell

ghc:
  - 7.8
  - 7.6

before_install:
  - sudo apt-get install msgpack-python

script:
  # Travis default from http://docs.travis-ci.com/user/languages/haskell/
  - cabal configure --enable-tests && cabal build
  - python test.py
