language: haskell

ghc:
  - 7.8
  - 7.6

before_install:
  - sudo apt-get install msgpack-python

install:
  - cabal install --only-dependencies --enable-tests --enable-shared

script:
  - cabal configure --enable-tests --enable-shared
  - cabal build
  - python test.py
